export const UPDATE_FEED_TIME_START = "UPDATE_FEED_TIME_START";
export const UPDATE_FEED_AMOUNT = "UPDATE_FEED_AMOUNT";
export const UPDATE_CURRENT_TIME = "UPDATE_CURRENT_TIME";
export const ADD_FEED = "ADD_FEED";

export const UPDATE_SLEEP_TIME_START = "UPDATE_SLEEP_TIME_START";
export const UPDATE_SLEEP_STATUS = "UPDATE_SLEEP_STATUS";
