export const UPDATE_FEED_TIME_START = "UPDATE_FEED_TIME_START";
export const UPDATE_FEED_AMOUNT = "UPDATE_FEED_AMOUNT";
export const UPDATE_CURRENT_TIME = "UPDATE_CURRENT_TIME";
export const ADD_FEED = "ADD_FEED";

export const UPDATE_SLEEP_STATUS = "UPDATE_SLEEP_STATUS";
export const ADD_SLEEP_START = "ADD_SLEEP_START";
export const ADD_SLEEP_END = "ADD_SLEEP_END";
export const ADD_SLEEP_DURATION = "ADD_SLEEP_DURATION";
